#spring.datasource.url=jdbc:mysql://db4free.net:3306/gsbka_store
#spring.datasource.username=gsbka_store
#spring.datasource.password=#zZUIvu183ZiBViH5yFewnE6BzmnuSukU@
#mybatis.mapper-locations=classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/gsbka_store
    username: gsbka_store
    password: "#zZUIvu183ZiBViH5yFewnE6BzmnuSukU@"
  jackson:
    default-property-inclusion: non_null

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/store
#    username: root
#    password:
#  jackson:
#    default-property-inclusion: non_null

server:
  port: 8005

mybatis:
  mapper-locations: classpath:mapper/*.xml

